### ISSUE TITLE
运行大神这个demo，手机会卡

### ISSUE THREAD

**Issue by ghost** [isuperqiang/AndroidKeepLivePractice#1]
大神这个保活做的很不错，运行后，下拉通知栏，明显觉得会很卡，在很多机型上卡爆了，具体原因大概是不断的在做 开启 JobService 定时  我把这段代码放在了onCreate里面就不卡了，但是保活缺不怎么样，大神有什么思路没

**Comment by isuperqiang** [comment]
下拉通知栏会卡，原因很可能是多次开启前台服务，尝试把开启前台服务放到 onCreate 里面做试试，应该会好一些。

**Comment by ghost** [comment]
嗯嗯，放到onCreate里面做确实是不卡了，但是不会保活，简单的做一次内存清除就没了

**Comment by isuperqiang** [comment]
保活这种东西，随着系统的升级越来越难做，为了优化体验，谷歌不会妥协的
